### ISSUE TITLE
Handicap mode

### ISSUE THREAD

**Issue by deathsythe47** [deathsythe47/base_entranced#116]

**Comment by Avygeil** [comment]
just pick onasi

**Comment by deathsythe47** [comment]
What would be the best way to do this?

I'm thinking that, say you are playing 3v4, the guys on the 3-player team should deal +33% damage, and the guys on the 4-player team should deal -33% damage.

**Comment by deathsythe47** [comment]
f743fa96eccfec532f3a8ce1060d6c4b6ca48dd2
